// Code generated by entc, DO NOT EDIT.

package note

import (
	"demo/domain"
	"demo/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldText), v))
	})
}

// ExternalReference applies equality check predicate on the "external_reference" field. It's identical to ExternalReferenceEQ.
func ExternalReference(v *domain.ExternalReference) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExternalReference), v))
	})
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldText), v))
	})
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldText), v))
	})
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.Note {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Note(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldText), v...))
	})
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.Note {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Note(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldText), v...))
	})
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldText), v))
	})
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldText), v))
	})
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldText), v))
	})
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldText), v))
	})
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldText), v))
	})
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldText), v))
	})
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldText), v))
	})
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldText), v))
	})
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldText), v))
	})
}

// ExternalReferenceEQ applies the EQ predicate on the "external_reference" field.
func ExternalReferenceEQ(v *domain.ExternalReference) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldExternalReference), v))
	})
}

// ExternalReferenceNEQ applies the NEQ predicate on the "external_reference" field.
func ExternalReferenceNEQ(v *domain.ExternalReference) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldExternalReference), v))
	})
}

// ExternalReferenceIn applies the In predicate on the "external_reference" field.
func ExternalReferenceIn(vs ...*domain.ExternalReference) predicate.Note {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Note(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldExternalReference), v...))
	})
}

// ExternalReferenceNotIn applies the NotIn predicate on the "external_reference" field.
func ExternalReferenceNotIn(vs ...*domain.ExternalReference) predicate.Note {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Note(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldExternalReference), v...))
	})
}

// ExternalReferenceGT applies the GT predicate on the "external_reference" field.
func ExternalReferenceGT(v *domain.ExternalReference) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldExternalReference), v))
	})
}

// ExternalReferenceGTE applies the GTE predicate on the "external_reference" field.
func ExternalReferenceGTE(v *domain.ExternalReference) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldExternalReference), v))
	})
}

// ExternalReferenceLT applies the LT predicate on the "external_reference" field.
func ExternalReferenceLT(v *domain.ExternalReference) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldExternalReference), v))
	})
}

// ExternalReferenceLTE applies the LTE predicate on the "external_reference" field.
func ExternalReferenceLTE(v *domain.ExternalReference) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldExternalReference), v))
	})
}

// ExternalReferenceContains applies the Contains predicate on the "external_reference" field.
func ExternalReferenceContains(v *domain.ExternalReference) predicate.Note {
	vc := v.String()
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldExternalReference), vc))
	})
}

// ExternalReferenceHasPrefix applies the HasPrefix predicate on the "external_reference" field.
func ExternalReferenceHasPrefix(v *domain.ExternalReference) predicate.Note {
	vc := v.String()
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldExternalReference), vc))
	})
}

// ExternalReferenceHasSuffix applies the HasSuffix predicate on the "external_reference" field.
func ExternalReferenceHasSuffix(v *domain.ExternalReference) predicate.Note {
	vc := v.String()
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldExternalReference), vc))
	})
}

// ExternalReferenceIsNil applies the IsNil predicate on the "external_reference" field.
func ExternalReferenceIsNil() predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldExternalReference)))
	})
}

// ExternalReferenceNotNil applies the NotNil predicate on the "external_reference" field.
func ExternalReferenceNotNil() predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldExternalReference)))
	})
}

// ExternalReferenceEqualFold applies the EqualFold predicate on the "external_reference" field.
func ExternalReferenceEqualFold(v *domain.ExternalReference) predicate.Note {
	vc := v.String()
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldExternalReference), vc))
	})
}

// ExternalReferenceContainsFold applies the ContainsFold predicate on the "external_reference" field.
func ExternalReferenceContainsFold(v *domain.ExternalReference) predicate.Note {
	vc := v.String()
	return predicate.Note(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldExternalReference), vc))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Note) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Note) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Note) predicate.Note {
	return predicate.Note(func(s *sql.Selector) {
		p(s.Not())
	})
}
