// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in demo/ent/runtime.go

const (
	Version = "v0.7.1-0.20210411114748-f59e25d22865"            // Version of ent codegen.
	Sum     = "h1:e7PKVI3TcF7P7rCLOSr6uOBkfttUQiHtF80XH+zkcdg=" // Sum of ent codegen.
)
