// Code generated by entc, DO NOT EDIT.

package ent

import (
	"demo/ent/note"
	"demo/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	noteFields := schema.Note{}.Fields()
	_ = noteFields
	// noteDescText is the schema descriptor for text field.
	noteDescText := noteFields[0].Descriptor()
	// note.TextValidator is a validator for the "text" field. It is called by the builders before save.
	note.TextValidator = noteDescText.Validators[0].(func(string) error)
}
